version: "3.7"
services:


  mz-nginx:
    image: nginx:alpine
    container_name: mz-apigateway-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www
      - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mz_bridge

  nbs-fpm:
    build:
      args:
        user: mz_u
        uid: 1000
      context: ./
      dockerfile: docker/Fpm.Dockerfile
    image: mz-api-gateway
    container_name: mz-apigateway-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mz_bridge

networks:
  mz_bridge:
    external: true
